version: '3.8'

services:
# 
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - '5432'
# 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
# 
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - react_value:/frontend/build
    ports:
      - "3000:3000"
# 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_value:/var/html/react
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
# 
volumes:
  db_value:
  react_value:
  static_value:
  media_value:
