version: '3.8'

services:
  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./tasks_value:/app/tasks
    command: python -m celery -A config.celery worker -l INFO

  celery-beats:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db_value:/var/lib/postgresql/data/
    command: python -m celery -A config.celery beat -l INFO

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
      - worker
      - celery-beats
      - backend

  #
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - '5432'
# 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
# 
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - react_value:/frontend/build
    ports:
      - "3000:3000"
# 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_value:/var/html/react
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
      - worker
      - flower
# 
volumes:
  db_value:
  tasks_value:
  react_value:
  static_value:
  media_value:
