version: '3.8'

services:
# 
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
# 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
# 
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - react_build:/frontend/build
# 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/react
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
# 
volumes:
  react_build:
  static_value:
  media_value:
