# Generated by Django 4.1.4 on 2022-12-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_image_options_alter_newsitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
