# Generated by Django 4.1.4 on 2022-12-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_image_image_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_b64',
        ),
    ]
