# Generated by Django 4.1.4 on 2022-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_image_image_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
